trigger:
- main

pool:
  name: Default

variables:
  buildConfiguration: 'Release'

steps:

- task: UseDotNet@2
  displayName: 'Install .NET 8'
  inputs:
    packageType: 'sdk'
    version: '8.x'

- script: dotnet restore
  displayName: 'Restore packages'

- script: dotnet build --configuration $(buildConfiguration) --no-restore
  displayName: 'Build project'

- script: dotnet pack --configuration $(buildConfiguration) --no-build --output $(Build.ArtifactStagingDirectory)
  displayName: 'Pack NuGet package'

- task: NuGetAuthenticate@1
  displayName: 'Authenticate NuGet'

- task: NuGetCommand@2
  displayName: 'Push NuGet package'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'jkau1146'
    allowPackageConflicts: true